### PR TITLE
Add support for partial package.json files

### PR DESCRIPTION
**Pull request by Gaulomatic**
I have added support for partial `package.json` files (such as `package.angular.json`)that are going to be merged in preinstall.

### CODE REVIEW

**Comment by pflannery** [comment]
@Gaulomatic Thanks for creating this PR. 

Where do partial package.*.json files get used? can you give me an example as I've not heard of them before.

**Comment by Gaulomatic** [comment]
There is no standard for them. I use them in large projects to keep track of why I need a package and group them accordingly. I find it hard to navigate through package.json files with 100 lines or more, especially when the lense is enabled (even on my 65" screen).

For example, I put all Angular related stuff into a separate file, all ngrx packages into another, and so on. Then I run a script using `package-json-merge` before install to merge them into one single, giant package.json.

Example file list

package json

Preinstall command inside `package.json`

preinstall

merge.js file using `package-json-merge` (available from npm)

merge js

And content of `package.ngrx.json`

ngrx

I just thought it would be nice to have inspections in these partial files as well, since it's so practical to keep track of outdated packages, update them et cetera.

**Comment by pflannery** [comment]
Can you add a smoke test? 

Same or Similar as the "package.ngrx.json" example you put in your last comments is fine.

Smokes for npm go [here](https://github.com/vscode-contrib/vscode-versionlens/tree/master/test/smoke/npm)

**Comment by pflannery** [comment]
Closing due to inactivity.

**Pull request closed without merging**
