### PR TITLE
dotnet: Filter to use only enabled sources

### PR DESCRIPTION
**Pull request by Hoffs**
So while it did parse whether the source was disabled (starting with D) it did not do anything about it, so it would still try to use sources that are disabled. This just filters them out in the provider. Unless that was intended behavior.

### CODE REVIEW

**Comment by pflannery** [comment]
I dont think we need this check because fetchSources already filters out disabled sources [here](https://github.com/vscode-contrib/vscode-versionlens/blob/master/src/infrastructure/providers/dotnet/clients/dotnetClient.ts#L30-L33).

The test for that is [here](https://github.com/vscode-contrib/vscode-versionlens/blob/master/test/unit/infrastructure/providers/dotnet/clients/dotnetClient.tests.ts#L97-L124)

or am I missing something?

**Comment by Hoffs** [comment]
> I dont think we need this check because fetchSources already filters out disabled sources [here](https://github.com/vscode-contrib/vscode-versionlens/blob/master/src/infrastructure/providers/dotnet/clients/dotnetClient.ts#L30-L33).
> 
> The test for that is [here](https://github.com/vscode-contrib/vscode-versionlens/blob/master/test/unit/infrastructure/providers/dotnet/clients/dotnetClient.tests.ts#L97-L124)
> 
> or am I missing something?

That checks if there is at least one `E`, it doesn't handle or test cases with multiple sources, eg:
```
D https://api.nuget.org/v3/index.json
E http://localhost:8081/repository/nuget-proxy-v3/index.json
EM C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```
There is enabled source but there are also disabled one, it will still try to use disabled source.

**Comment by pflannery** [comment]
@Hoffs ooooh gotcha. 

yeah thats not quite enough lol.

Be nicer if we can filter just after [parseSourcesArray](https://github.com/vscode-contrib/vscode-versionlens/blob/7bc7bd586ce58d993db7e56d654cbb3ff9377233/src/infrastructure/providers/dotnet/clients/dotnetClient.ts#L43)

something like:

```js
return parseSourcesArray(lines).filter(s => s.enabled);
```

**Comment by pflannery** [comment]
@Hoffs looks good! thanks

**Pull request merged**
