### PR TITLE
Migrate to resolving services from NuGet feed index

### PR DESCRIPTION
**Pull request by Hoffs**
Instead of relying on `SearchAutocompleteService` this change allows use to specific nuget v3 index url and then the extension will automatically resolve available service from list of supported services. Additionally `SearchAutocompleteService` is not a required service (so artifactory and such might not even have such endpoint).

Currently supports:
```
PackageBaseAddress
SearchAutocompleteService
RegistrationsBaseUrl
SearchQueryService
```
from: https://docs.microsoft.com/en-us/nuget/api/overview

Code is structured in a way that should allow easy addition of others service.

One downside with how it is implemented is that it requires at least 2 requests, 1 for feed index, next one for actual service.

### CODE REVIEW

**Comment by lafriks** [comment]
What could be done to get this merged?

**Comment by pflannery** [comment]
I do want these changes but cant land at the moment because i'm in the process of updating to a clean architecture. https://github.com/vscode-contrib/vscode-versionlens/tree/clean-arch

Would be nice to have all the nuget client could be wrapped in to a package. 
I saw ths client https://github.com/tintoy/nuget-client-nodejs

At some point I also want to use the `dotnet nuget list source` output to get the user feeds for the current project....unless teir is a client out there that can do that too.

**Comment by Hoffs** [comment]
> Would be nice to use a nuget client as a package.
> I saw this client https://github.com/tintoy/nuget-client-nodejs

Quick look at the source, v3 api is based on `SearchAutocompleteService`, and based on https://docs.microsoft.com/en-us/nuget/api/overview `SearchAutocompleteService` is not required service.

**Comment by pflannery** [comment]
@Hoffs Thank you for the effort you put in to this. Sorry that I never got this PR merged. 

Nuget service resolution is now part of v1.0.0.  You can see the [changelog for more info](https://github.com/vscode-contrib/vscode-versionlens/blob/master/CHANGELOG.md#100)

**Comment by Hoffs** [comment]
As far as I can see it still only supports `SearchAutocompleteService` which is not required nuget service?

**Pull request closed without merging**
