### PR TITLE
 Supports composer #73

### LINKED ISSUE #73: support composer
Hi,

I like the extension, but I'm missing support for my php projects. Are you fine with that change? I can provide a pr for you if you want to.

Thanks!
Jens

### PR DESCRIPTION
**Pull request by Cerzat43**
Capture d’écran de 2019-06-14 17-33-47

In a future pull request, it would be a good idea to manage the required tools (ex: `"php": "^7.1.3"`) and private or others repositories like wpackagist.org.

closes #73

### CODE REVIEW

**Comment by pflannery** [comment]
@Cerzat43 Thanks for this PR. can you reolve the conflicts by rebasing with latest master. I can then review this. thanks

**Comment by Cerzat43** [comment]
Conflicts are resolved.
You can review @pflannery

**Comment by mikestecker** [comment]
Would love to see this updated! Any news?

**Comment by Cerzat43** [comment]
I'm waiting for the review

**Comment by jonom** [comment]
@pflannery anything we can do from outside to help move this along?

**Comment by w3bdesign** [comment]
@pflannery Any possibility to get this added?

**Comment by pflannery** [comment]
@Cerzat43 Great thanks for this work. Sorry for the long delay.
@w3bdesign Just updated and deployed this in v0.25.0

**Pull request merged**
