### PR TITLE
feat: Support Flutter/Dart #130

### PR DESCRIPTION
**Pull request by Gorniv**
Support Flutter/Dart

### CODE REVIEW

**Comment by pflannery** [comment]
@Gorniv Thanks for this contribution, its looking good so far. I would love to see some tests.
Some smoke tests too like [these](https://github.com/vscode-contrib/vscode-versionlens/tree/master/test/smoke)

**Comment by Gorniv** [comment]
@pflannery I added tests

**Comment by Gorniv** [comment]
@pflannery is it ok?

**Comment by MegaMattMiller** [comment]
@Gorniv since this issue has been opened the URL for pub has changed to https://pub.dev/ from https://pub.dartlang.org/

Might want to update the README.

Can't wait to use this once it's merged!

**Comment by Gorniv** [comment]
@MegaMattMiller done.
You can install [wait pr ext](https://marketplace.visualstudio.com/items?itemName=gornivv.dart-versionlens) now.
When this pr will be merged - I remove [wait pr ext](https://marketplace.visualstudio.com/items?itemName=gornivv.dart-versionlens) =)

**Comment by pflannery** [comment]
@Gorniv This looks great! thanks...
Can you remove all files and folders accidentally checked in to this PR? 
```project.AssemblyInfoInputs.cache``` and ```project.AssemblyInfo.cs```

**Comment by Gorniv** [comment]
@pflannery sorry for 'dotnet/obj' :)
Is it good?

**Comment by MegaMattMiller** [comment]
@Gorniv would there be any way to change the default pub server location via a settings file? My company has a pub server that uses the same API as pub.dev where all of our private packages live.

**Comment by pflannery** [comment]
> @Gorniv would there be any way to change the default pub server location via a settings file? My company has a pub server that uses the same API as pub.dev where all of our private packages live.

@Gorniv If this is something you can do now as I can wait if it is? otherwise I will merge as is and open a feature for this.

**Comment by Gorniv** [comment]
@pflannery megre now please.
@MegaMattMiller  please create issues with example settings.

**Comment by MegaMattMiller** [comment]
@Gorniv easy peasy! Thanks!

**Comment by pflannery** [comment]
@Gorniv Thanks for you hard work on this...I've published this in 0.24.0

**Pull request merged**
