### PR TITLE
Adds support for jspm in package.json

### PR DESCRIPTION
**Pull request by eamodio**

### CODE REVIEW

**Comment by pflannery** [comment]
@eamodio thanks for the contribute. 

Can you add a smoke test for this?

**Comment by pflannery** [comment]
also, I've run the unit tests locally and I see four tests are failing.

**Comment by eamodio** [comment]
@pflannery I've fixed up the unit tests and added jspm examples to the npm smoke (not sure where the smoke tests are though).

**Comment by pflannery** [comment]
@eamodio the smoke tests live here - https://github.com/vscode-contrib/vscode-versionlens/tree/master/test/smoke

**Comment by eamodio** [comment]
@pflannery I only see json files in there -- and I added jspm stuff to the npm file. Not sure what else you want there.

**Comment by pflannery** [comment]
@eamodio that's perfect! thanks

**Pull request merged**
